table Superstore
	lineageTag: 64af480f-8d13-4d5a-b525-15170d7d1a35

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 7a0c6247-a5e6-4d60-b6dc-8cde6bc1165e
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 405a5c3f-1ced-4ca0-ad57-3cf72627e998
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: edad7b2a-e66b-4ab8-ac1e-49093cde7739
		summarizeBy: none
		sourceColumn: Order Date

		variation Variation
			isDefault
			relationship: d16a9ba4-ffb7-4854-a677-791d25134ccb
			defaultHierarchy: LocalDateTable_c72f8c37-82bc-470c-a3dd-8fd6e450c5df.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 160d4706-a6b6-48c4-b375-b74f855464b6
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: c291c348-0d6c-4487-b044-b800e347fe79
			defaultHierarchy: LocalDateTable_4f9758aa-9b02-43a8-ac74-f12e601d65e7.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: e5cc7f35-dc58-41fa-be72-0ce0baa68d4f
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: e8286b58-136c-4790-afc2-244c67bd1aa1
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 53a6e6fd-3a00-4faf-a71f-9e6a103fe225
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 26aecf3d-f5ce-4c57-b811-8f86dbb2dd65
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country
		dataType: string
		lineageTag: 357fd666-dec5-4eb3-888a-d96010fa2ded
		summarizeBy: none
		sourceColumn: Country

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 266ae160-34c0-46b3-864d-8eaae126b4b9
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State
		dataType: string
		lineageTag: d17b0d61-eb01-4af6-a466-a43b235796a2
		summarizeBy: none
		sourceColumn: State

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: int64
		formatString: 0
		lineageTag: 421e3a24-7b12-4acc-b94a-35134b53cf48
		summarizeBy: count
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 48ccc776-dbdb-4831-b895-69a7a4908ce4
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: ff5f979c-04c1-4246-9d77-4b3fb4ba63b5
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: ae084e56-f2a3-40fb-a8f9-0a0246dab947
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: 96bec4f4-c91f-4402-ad02-ce811863bbc6
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 0975b760-7091-47b4-af9f-cea4d4693e00
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: c7eb9325-de2f-4c19-8bd6-f35f34b10adc
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: 4b6b2498-611c-4df2-a264-c823290f24bc
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 195b229c-156b-4745-bd85-66834c9b50a7
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: d609b6c3-ea31-4bb4-90dc-6da30cfb63a6
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Superstore = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("H:\My Drive\NCKH\Enhanced_EDA_Visualization\superstore.csv"),[Delimiter=",", Columns=21, Encoding=65001, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country", type text}, {"City", type text}, {"State", type text}, {"Postal Code", Int64.Type}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	changedProperty = Name

	annotation PBI_ResultType = Table

